language: ruby
rvm:
  - 2.2.2
before_install: gem install bundler -v 1.11.2
services:
  - postgresql
before_script:
  - psql -c "CREATE USER agenda-online WITH PASSWORD '';" -U postgres
  - psql -c 'create database agenda-online_test;' -U agenda-online