language: ruby
rvm:
  - 2.2.2
before_install: gem install bundler -v 1.11.2
services:
  - postgresql
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database agenda-online_test;' -U postgres
  - cp config/database.yml.travis config/database.yml